"""add to foreign keys to action_logs

Revision ID: 9d5a872c87f4
Revises: 7ddff8f23c2c
Create Date: 2026-06-22 13:48:06.130877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d5a872c87f4'
down_revision: Union[str, None] = '7ddff8f23c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'action_logs', 'contents', ['content_id'], ['id'])
    op.create_foreign_key(None, 'action_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'action_logs', type_='foreignkey')
    op.drop_constraint(None, 'action_logs', type_='foreignkey')
    # ### end Alembic commands ###
