






name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

  
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: analytics_db
        ports:
          - 5432:5432
    
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

      kafka:
        image: apache/kafka:3.7.0
        env:
          KAFKA_NODE_ID: 1
          KAFKA_PROCESS_ROLES: broker,controller
          KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
          KAFKA_LISTENERS: "PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093"
          KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
          KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
          CLUSTER_ID: "U4jap6-ZTBidfX3wv3vwVg"
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        ports:
          - 9092:9092
    steps:
      - name: Check code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Create test database
        env:
          PGPASSWORD: postgres
        run: psql -h localhost -U postgres -c "CREATE DATABASE test_db;"

      - name: Run tests
        env:
          TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          KAFKA_BOOTSTRAP_SERVERS: localhost:9092
        run: pytest tests/ -v

      - name: Start FastAPI and run health check
        env:
            DATABASE_URL: postgresql://postgres:postgres@localhost:5432/analytics_db
            REDIS_URL: redis://localhost:6379/0
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            KAFKA_BOOTSTRAP_SERVERS: localhost:9092
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 10
          curl -f http://localhost:8000/ || exit 1
      